services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 443:443
      - 80:80    
    volumes:
      - type: bind
        source: /etc/letsencrypt/
        target: /etc/letsencrypt/
  djangoapp:
    build:
      dockerfile: Dockerfile.prod
